version: "3.2"

services:
  api:
    container_name: EindWerkDev
    build: ./
    environment:
      PG_CONNECTION_STRING: postgres://example:example@store:5432/test

    ports:
      - 3100:3000
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: sportagenda
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432